#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := evade-2

EXTRA_CFLAGS += --save-temps -DLIBXMP_CORE_PLAYER -DLIBXMP_CORE_DISABLE_IT -D__ESP_32__



include $(IDF_PATH)/make/project.mk
